# Generated by Django 6.0.6 on 2026-06-06 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('roof_length', models.FloatField(help_text='Length in meters')),
                ('roof_width', models.FloatField(help_text='Width in meters')),
                ('monthly_electricity_bill', models.FloatField(help_text='Monthly bill in local currency')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_generation_kwh', models.FloatField(default=0.0)),
                ('monthly_generation_kwh', models.FloatField(default=0.0)),
                ('annual_generation_kwh', models.FloatField(default=0.0)),
                ('panels_required', models.IntegerField(default=0)),
                ('installation_cost', models.FloatField(default=0.0)),
                ('annual_savings', models.FloatField(default=0.0)),
                ('payback_period_years', models.FloatField(default=0.0)),
                ('savings_10_years', models.FloatField(default=0.0)),
                ('savings_25_years', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='solar_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_score', models.FloatField(default=0.0, help_text='0-10 Score')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Percentage')),
                ('usable_rooftop_area', models.FloatField(default=0.0, help_text='Square meters')),
                ('suitable_zones', models.IntegerField(default=0)),
                ('unsuitable_zones', models.IntegerField(default=0)),
                ('light_intensity_percentage', models.FloatField(default=0.0)),
                ('shadow_coverage_percentage', models.FloatField(default=0.0)),
                ('obstacle_data', models.JSONField(default=dict, help_text='JSON mapping of detected obstacles')),
                ('recommended_panel_orientation', models.CharField(default='South', max_length=100)),
                ('recommended_system_size_kw', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='solar_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='solar_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='solar_projects.project')),
            ],
        ),
    ]
