# Generated by Django 6.0.6 on 2026-06-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='panel_type',
            field=models.CharField(default='Standard', help_text='Standard, Premium, Ultra', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='roof_azimuth',
            field=models.CharField(default='South', help_text='Direction roof faces', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='roof_pitch',
            field=models.FloatField(default=20.0, help_text='Roof pitch/angle in degrees'),
        ),
    ]
