# Generated by Django 6.0.6 on 2026-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_projects', '0002_project_panel_type_project_roof_azimuth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI generated natural language description', null=True),
        ),
    ]
